language: php
php:
  - 7.3

notifications:
  email: false

cache:
  directories:
    - ~/.composer/cache/files
    - vendor

install:
  - composer install

script:
  - make run-phpstan
  - make run-phpunit
  - make run-php-cs-fixer@travis
